---
apiVersion: v1
kind: Secret
metadata:
  name: nacos-passwd
type: Opaque
data:
  password: {{ .Values.nacos.password | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-config
data:
  nacosHost: "{{ .Values.nacos.host }}"
  nacosPort: "{{ .Values.nacos.port }}"
  nacosUsername: "{{ .Values.nacos.username }}"
  nacosNamespace: "{{ .Values.nacos.namespace }}"
  nacosGroup: "{{ .Values.nacos.group }}"
  