{{- if .Values.modules.drugstorage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.drugstorage.name }}
  labels:
    {{- include "ctyk-yjk.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.image.drugstorage.port }}
      targetPort: {{ .Values.image.drugstorage.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.image.drugstorage.name }}
{{- end }}