---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ .Values.image.kuboard.name }}
    {{- include "kuboard.labels" . | nindent 4 }}
  name: {{ .Values.image.kuboard.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.image.kuboard.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.kuboard.name }}
    spec:
      containers:
        - name: {{ .Values.image.kuboard.name }}
          env:
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          image: "{{ .Values.image.kuboard.repository }}:{{ .Values.image.kuboard.tag }}"
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 15
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 1
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
          startupProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 80
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.name }}
            readOnly: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
