apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: {{ .Values.image.kuboard.name }}
  name: {{ .Values.image.kuboard.name }}
spec:
  clusterIP:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: web
      nodePort: {{ .Values.externalPort }}
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: {{ .Values.image.kuboard.name }}
  sessionAffinity: None
  type: NodePort
