# 副本数
replicaCount: 1

global:
  ## @param global.imageRegistry Global Docker image registry
  imageRegistry: ""
  ## Optionally specify an array of imagePullSecrets.
  ## Example:
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  imagePullSecrets: []

image:
  appCpms:
    name: ctyk-cpms-app-cpms
    repository: 'k3s.harbor:8090/sync/yjk-release-docker/smart-hospital/server/ctyk-yjk-cpms-app-cpms'
    tag: "v1.7.0-release-tag"   ## TODO: 修改为实际版本号
    port: 20256
  aggregateZyemr:
    name: ctyk-middle-aggregate-zyemr
    repository: 'k3s.harbor:8090/sync/yjk-release-docker/smart-hospital/server/ctyk-yjk-middle-aggregate-zyemr'
    tag: "v1.7.10-release-tag"   ## TODO: 修改为实际版本号
    port: 20252
  businessApply:
    name: ctyk-middle-business-apply
    repository: 'k3s.harbor:8090/sync/yjk-release-docker/smart-hospital/server/ctyk-yjk-middle-business-apply'
    tag: "v1.7.10-release-tag"   ## TODO: 修改为实际版本号
    port: 20255
  businessCpms:
    name: ctyk-middle-business-cpms
    repository: 'k3s.harbor:8090/sync/yjk-release-docker/smart-hospital/server/ctyk-yjk-middle-business-cpms'
    tag: "v1.7.0-release-tag"   ## TODO: 修改为实际版本号
    port: 20257
  businessZyemr:
    name: ctyk-middle-business-zyemr
    repository: 'k3s.harbor:8090/sync/yjk-release-docker/smart-hospital/server/ctyk-yjk-middle-business-zyemr'
    tag: "v1.7.0-release-tag"   ## TODO: 修改为实际版本号
    port: 20254
  businessZyorder:
    name: ctyk-middle-business-zyorder
    repository: 'k3s.harbor:8090/sync/yjk-release-docker/smart-hospital/server/ctyk-yjk-middle-business-zyorder'
    tag: "v1.7.10-release-tag"   ## TODO: 修改为实际版本号
    port: 20253
  appApply:
    name: ctyk-zyemr-app-apply
    repository: 'k3s.harbor:8090/sync/yjk-release-docker/smart-hospital/server/ctyk-yjk-zyemr-app-apply'
    tag: "v1.7.8-release-tag"   ## TODO: 修改为实际版本号
    port: 20251
  appZyemr:
    name: ctyk-zyemr-app-zyemr
    repository: 'k3s.harbor:8090/sync/yjk-release-docker/smart-hospital/server/ctyk-yjk-zyemr-app-zyemr'
    tag: "v1.7.1-release-tag"   ## TODO: 修改为实际版本号
    port: 20250

env:
  - name: "TZ"
    value: "Asia/Shanghai"
  - name: PROFILE
    value: "prod"
  - name: JAVA_OPTS
    value: "-server -Xms1G -Xmx1G -Xmn512M"

isGray: "false"  # TODO: 是否为灰度版本,灰度版本会在变量中添加Dyk_gray=true
skywalking:
  enabled: false   #TODO: 开启skywalking，前提是已经部署过skywalking oap服务,否则设为false
nameOverride: ""
fullnameOverride: ""

resources:
  requests:
    cpu: 100m
    memory: 1Gi
  limits:
    cpu: 4
    memory: 2Gi

updateStrategy:
  type: RollingUpdate

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

nodeSelector: {}

tolerations: []
