---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: {{ .Values.web.name }}
  name: {{ .Values.web.name }}
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: {{ .Values.web.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.web.name }}
    spec:
      containers:
        - name: {{ .Values.web.name }}
          env:
            - name: JAVA_OPTS
              value: >-
                -Xms512M -Xmx1G
                -Drocketmq.namesrv.addr={{ include "rocketmq-nameserver.fullname" . }}:9876
          {{- toYaml .Values.web.env | nindent 12 }}
          image: "{{ .Values.web.image.repository }}:{{ .Values.web.image.tag }}"
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
          {{- toYaml .Values.web.resources | nindent 12 }}
          startupProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /tmp/rocketmq-console/data/users.properties
              name: volume-rocketmq-console
              subPath: users.properties
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      volumes:
        - configMap:
            defaultMode: 420
            name: mqconsole-user
          name: volume-rocketmq-console
