apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: {{ .Values.web.name }}
  name: {{ .Values.web.name }}
spec:
  clusterIP:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: {{ .Values.web.externalPort }}
  selector:
    app: {{ .Values.web.name }}
  type: NodePort