apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.main.name }}
  labels:
    {{- include "ctyk-yjk.labels" . | nindent 4 }}
spec:
  {{- if eq .Values.service.type "NodePort" }}
  type: NodePort
  {{- else }}
  type: ClusterIP
  {{- end }}
  ports:
    - port: {{ .Values.image.main.port }}
      targetPort: {{ .Values.image.main.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.externalPort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.image.main.name }}
