{{- if and (.Values.health) (eq .Values.image.ygtHealthResident.service.type "Ingress") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.image.ygtHealthResident.name }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: {{ .Values.service.ingressClassName }}
  rules:
  - host: {{ .Values.service.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.image.ygtHealthResident.name }}  ## 后端service服务名称
            port:
              number: {{ .Values.image.ygtHealthResident.port }}
{{- end }}