{{- if .Values.modules.pacsViewer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.pacsViewer.name }}
  labels:
    app: {{ .Values.image.pacsViewer.name }}
    {{- include "ctyk-yjk.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.image.pacsViewer.name }}
      {{- include "ctyk-yjk.selectorLabels" . | nindent 6 }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Values.image.pacsViewer.name }}
        {{- include "ctyk-yjk.selectorLabels" . | nindent 8 }}
    spec:
      {{- include "ctyk-yjk.imagePullSecrets" . | nindent 6 }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.image.pacsViewer.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.pacsViewer.repository }}:{{ .Values.image.pacsViewer.tag }}"
          imagePullPolicy: IfNotPresent
          {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end}}
          ports:
            - name: http
              containerPort: {{ .Values.image.pacsViewer.port }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            successThreshold: 1
            tcpSocket:
              port: {{ .Values.image.pacsViewer.port }}
            initialDelaySeconds: 5
            timeoutSeconds: 1 
            periodSeconds: 10
          readinessProbe:
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
            tcpSocket:
              port: {{ .Values.image.pacsViewer.port }}
          startupProbe:
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 1
            periodSeconds: 10
            tcpSocket:
              port: {{ .Values.image.pacsViewer.port }}
            initialDelaySeconds: 5
          resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Values.image.pacsViewer.name }}
                topologyKey: kubernetes.io/hostname
              weight: 60
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}