apiVersion: v1
kind: Service
metadata:
  annotations:
  {{- toYaml .Values.oap.service.annotations | indent 4 }}
  labels:
    app: {{ .Values.oap.name }}
  name: {{ .Values.oap.name }}
spec:
  clusterIP:
  ports:
  {{- range $key, $value := .Values.oap.ports }}
    - name: {{ $key }}
      port: {{ $value }}
      protocol: TCP
      targetPort: {{ $value }}
  {{- end }}
  selector:
    app: {{ .Values.oap.name }}
  type: {{ .Values.oap.service.type }}