apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: {{ .Values.ui.name }}
  name: {{ .Values.ui.name }}
spec:
  clusterIP:
  ports:
    - name: web
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ .Values.ui.name }}
  type: ClusterIP