apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.basePayment.name }}
  labels:
    {{- include "ctyk-yjk.labels" . | nindent 4 }}
  annotations:
    prometheus.io/port: {{ .Values.image.basePayment.port | quote }}  #prometheus监控端口
    prometheus.io/spring: "true"
    prometheus.io/path: "actuator/prometheus"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.image.basePayment.port }}
      targetPort: {{ .Values.image.basePayment.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.image.basePayment.name }}
